@startuml repopackage
!pragma useIntermediatePackages false

abstract class repopackage.cli.command_types.CommandBase {
}
class repopackage.workflow.workspace.Workspace {
  root: Path
  desk: Desk
  drawers: Drawers
}
class repopackage.workflow.phase.Phase {
  id: str
  workspace: None
}
class repopackage.workflow.phase.EvalResult {
  passed: int {static}
  failed: int {static}
  output: str {static}
  success: bool {static}
}
class repopackage.workflow.desk.Desk {
  workspace: None
  tasks: TaskCollection
  pills: PillCollection
}
class repopackage.workflow.desk.TaskCollection {
  workspace: None
}
class repopackage.workflow.desk.PillCollection {
  workspace: None
}
class repopackage.workflow.drawers.Drawers {
  workspace: None
}
class repopackage.workflow.drawers.DrawerSpec {
  id: str {static}
  title: str {static}
  domain: str {static}
  path: pathlib._local.Path {static}
  status: str {static}
}
class repopackage.workflow.task.WorkflowTask {
  model: TaskModel
  path: Path
  workspace: None
}
class repopackage.workflow.pill.WorkflowPill {
  model: PillModel
  path: Path
  workspace: None
}
class repopackage.cli.models.pill.PillModel {
  title: str {static}
  metadata: PillMetadata {static}
  why: str {static}
  what: str {static}
  how: str {static}
  lifecycle: str {static}
}
class repopackage.cli.models.task.TaskModel {
  id: str {static}
  title: str {static}
  traits: List[str] {static}
  explanation: str {static}
  reference: List[str] {static}
  what_to_fix: str {static}
  how_to_do_it: str {static}
  induced_changes: Optional[str] {static}
  depends_on: List[str] {static}
  priority: TaskPriority {static}
  status: TaskStatus {static}
  lifecycle: str {static}
  commit_sha: Optional[str] {static}
  phase: Optional[str] {static}
  pills: List[str] {static}
}
repopackage.workflow.workspace.Workspace *-- repopackage.workflow.desk.Desk
repopackage.workflow.workspace.Workspace *-- repopackage.workflow.drawers.Drawers
repopackage.workflow.desk.Desk *-- repopackage.workflow.desk.TaskCollection
repopackage.workflow.desk.Desk *-- repopackage.workflow.desk.PillCollection
repopackage.workflow.task.WorkflowTask *-- repopackage.cli.models.task.TaskModel
repopackage.workflow.pill.WorkflowPill *-- repopackage.cli.models.pill.PillModel
repopackage.cli.models.pill.PillModel *-- repopackage.cli.models.pill.PillMetadata
repopackage.cli.models.task.TaskModel *-- repopackage.cli.models.task.TaskPriority
repopackage.cli.models.task.TaskModel *-- repopackage.cli.models.task.TaskStatus
footer Generated by //py2puml//
@enduml
